version: "1"
services:
  - type: web
    name: personal-blog-api
    runtime: node
    plan: free
    rootDir: ./server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
